/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SnapshotDetailsImport } from './routes/snapshot-details'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const SnapshotDetailsLazyImport = createFileRoute('/snapshot-details')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SnapshotDetailsLazyRoute = SnapshotDetailsLazyImport.update({
  path: '/snapshot-details',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/snapshot-details').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/snapshot-details': {
      id: '/snapshot-details'
      path: '/snapshot-details'
      fullPath: '/snapshot-details'
      preLoaderRoute: typeof SnapshotDetailsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SnapshotDetailsLazyRoute,
})

/* prettier-ignore-end */
